[package]
name = "rust-swc-handler-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "Source/lib.rs"

[dependencies]
serde = "1"
swc_core = { version = "0.106.0", features = [
	"common",
	"ecma_utils",
	"ecma_plugin_transform",
] }
